# md2html 默认配置示例
source_dir: docs
output_dir: build/html
theme: github
clean_output: true
copy_static: true
metadata:
  title: Yitu
  description: 

# GitHub Pages 自定义域名下的路径前缀
base_url: /py-md

navigation_label: 我的文档
outline_label: 大纲
