name: github
label: GitHub 风格主题
description: GitHub Markdown 风格的响应式主题
template: base.html
pygments_style: friendly
default_hide_title: 点击展开
admonitions:
  note:
    title: 提示
  warning:
    title: 注意
